# Generated by Django 5.0.6 on 2024-05-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-id'], 'verbose_name': 'List', 'verbose_name_plural': 'Lists'},
        ),
        migrations.RenameField(
            model_name='list',
            old_name='name',
            new_name='title',
        ),
    ]
