# Generated by Django 5.0.6 on 2024-05-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-id'], 'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
    ]
